package com.serviconli.patientservice.model.enums;

import lombok.Getter;

@Getter
public enum NombreEps {

    EPS_SURA,
    COOSALUD_EPS_S,
    NUEVA_EPS,
    MUTUAL_SER,
    ALIANSALUD_EPS,
    SALUD_TOTAL_EPS_SA,
    EPS_SANITAS,
    FAMISANAR,
    SERVICIO_OCCIDENTAL_DE_SALUD_EPS_SOS,
    SALUD_MIA,
    COMFENALCO,
    COMPENSAR_EPS,
    EPM_EMPRESAS_PUBLICAS_DE_MEDELLIN,
    FONDO_DE_PASIVO_SOCIAL_DE_FERROCARRILES_NACIONALES_DE_COLOMBIA,
    CAJACOPI_ATLANTICO,
    CAPRESOCA,
    COMFACHOCO,
    COMFAMILIAR_DE_LA_GUAJIRA,
    COMFAORIENTE,
    EPS_FAMILIAR_DE_COLOMBIA,
    ASMET_SALUD,
    CAPITAL_SALUD_EPS_S,
    CONVIDA,
    SAVIA_SALUD_EPS,
    DUSAKAWI_EPSI,
    ASOCIACION_INDIGENA_DEL_CAUCA_EPSI,
    ANAS_WAYUU_EPSI,
    MALLAMAS_EPSI,
    PIJAOS_SALUD_EPS

}